language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      group: beta
    - os: osx 

r_packages:
  - covr
  - assertthat

r_github_packages:
  - hadley/devtools
  - hadley/testthat

after_success:
  - Rscript -e 'library(covr); codecov()'