language: r
cache: packages
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr
  - assertthat

r_github_packages:
  - hadley/devtools
  - hadley/testthat

after_success:
  - Rscript -e 'library(covr); codecov()'